from borealis.commands.my_info import CommandMyInfo
from borealis.commands.user_add import CommandUserAdd
from borealis.commands.user_remove import CommandUserRemove
from borealis.commands.user_update import CommandUserUpdate
from borealis.commands.user_info import CommandUserInfo
from borealis.commands.player_info import CommandPlayerInfo
from borealis.commands.player_notes import CommandPlayerNotes
from borealis.commands.silly_cats import CommandCats
from borealis.commands.silly_penguins import CommandPenguins
from borealis.commands.channel_add import CommandChannelAdd
from borealis.commands.channel_remove import CommandChannelRemove
from borealis.commands.channel_update import CommandChannelUpdate
from borealis.commands.help import CommandHelp
from borealis.commands.discord_strike import CommandDiscordStrike
from borealis.commands.debug_channel import CommandDebugChannel
from borealis.commands.server_status import CommandServerStatus
from borealis.commands.server_manifest import CommandServerManifest
from borealis.commands.server_staff import CommandServerStaff
from borealis.commands.server_pm import CommandServerPM
from borealis.commands.server_chars import CommandServerChars
from borealis.commands.server_commandreport import CommandServerCommandReport
from borealis.commands.server_faxlist import CommandServerFaxlist
from borealis.commands.server_getfax import CommandServerGetfax
from borealis.commands.server_who import CommandServerWho
from borealis.commands.server_restart import CommandServerRestart