from borealis.commands.MyInfo import commandMyInfo
from borealis.commands.UserAdd import commandUserAdd
from borealis.commands.UserRemove import commandUserRemove
from borealis.commands.UserUpdate import commandUserUpdate
from borealis.commands.PlayerInfo import commandPlayerInfo
from borealis.commands.PlayerNotes import commandPlayerNotes
from borealis.commands.SillyCats import commandCats
from borealis.commands.SillyPenguins import commandPenguins
from borealis.commands.ChannelAdd import commandChannelAdd
from borealis.commands.ChannelRemove import commandChannelRemove
from borealis.commands.ChannelUpdate import commandChannelUpdate
from borealis.commands.Help import commandHelp
from borealis.commands.DiscordStrike import commandDiscordStrike
