from borealis.commands.my_info import CommandMyInfo
from borealis.commands.user_add import CommandUserAdd
from borealis.commands.user_remove import CommandUserRemove
from borealis.commands.user_update import CommandUserUpdate
from borealis.commands.user_info import CommandUserInfo
from borealis.commands.player_info import CommandPlayerInfo
from borealis.commands.player_notes import CommandPlayerNotes
from borealis.commands.silly_cats import CommandCats
from borealis.commands.silly_penguins import CommandPenguins
from borealis.commands.channel_add import CommandChannelAdd
from borealis.commands.channel_remove import CommandChannelRemove
from borealis.commands.channel_update import CommandChannelUpdate
from borealis.commands.help import CommandHelp
from borealis.commands.discord_strike import CommandDiscordStrike
