language: python
dist: focal
python:
  - "3.8"

addons:
  mariadb: "10.5"

install:
  - pip install -r requirements.txt
  - cp ./travis/alembic.ini.travis ./alembic.ini
  - sudo mariadb -u root -e 'CREATE DATABASE borealis;'
  - sudo mariadb -u root -e "GRANT ALL PRIVILEGES ON borealis.* TO 'travis'@'%';"
  - sudo mariadb -u root -e "FLUSH PRIVILEGES;"

script:
  - python3 main.py --migrate_only
