"""Reworked role management

Revision ID: d98d1c398057
Revises: daaa2180b3e2
Create Date: 2020-11-21 19:26:41.403806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd98d1c398057'
down_revision = 'daaa2180b3e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managed_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('role_control_messages')
    op.add_column('guilds', sa.Column('role_management_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds', 'role_management_enabled')
    op.create_table('role_control_messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message_id', sa.INTEGER(), nullable=True),
    sa.Column('guild_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('managed_roles')
    # ### end Alembic commands ###
